<a href="https://colab.research.google.com/github/19PA1A0248/AI-Lab/blob/master/19PA1A0248_BHAVYA_SREE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#EXPERIMENT NO:-1 (NUMPY)


## i) Different ways to create numpy arrays

### method-1 to create NumPy arrays using lists


In [ ]:
import numpy as np
a = np.array([22,4,7]) #1-dimensional array
print(a)

[22  4  7]


### method-2 to create NumPy arrays

In [ ]:

import numpy as np
b = np.arange(55)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54]


### method-3 to create NumPy arrays

In [ ]:

import numpy as np
c = np.array([(22,4,48), (44,36,9)]) #2-dimensional arrays
print(c)

[[22  4 48]
 [44 36  9]]


### method-4 creates an arrays of all zero 

In [ ]:

np.zeros( (3,4) ) 


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### method-5 creates an array of all ones. dtype can also be specified

In [ ]:

np.ones( (2,3), dtype=np.int16 ) 


array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

## ii) Add, remove, modify elements in an array


### adding elements in an array

In [ ]:

import numpy as np
a = np.array([22,4])
b = np.append(a, [48])
print(b)

[22  4 48]


### removing elements in an array

In [ ]:

import numpy as np
x = np.array([22,4,48,44,36,9,7,45,46])
new_x = np.delete(x,[3,4,5])
print(new_x)

[22  4 48  7 45 46]


### modifying elements in an array 

In [ ]:

import numpy as np
x = np.array([22,4,48,44,36,9,7,45,46])
x[[3,4,5]] = [10,32,27]
print(x)

[22  4 48 10 32 27  7 45 46]


## iii) Arithmetic operations on NumPy arrays



In [ ]:
import numpy as np
# Let's create two arrays
a = np.array( [22,4,7,48] )
b = np.arange( 4 )
print(a)
print(b)

c = a-b # Simple substraction
print(c)

print(b**2) # Scalar multiplication(power)

print(10*np.sin(a)) # trignometric functions are available in numpy package

print(a<35) # Retuns true (or) false based on condition

a[0] +=10 # This is equalient to a[0]=a[0]+10

print(a)


[22  4  7 48]
[0 1 2 3]
[22  3  5 45]
[0 1 4 9]
[-0.08851309 -7.56802495  6.56986599 -7.68254661]
[ True  True  True False]
[32  4  7 48]





## iv) Slicing and Iterating of arrays


### Slicing of arrays:-

In [ ]:
import numpy as np
# Slicing a 1-D array

a=np.arange(22)**3
print(a)

print(a[4]) # Prints the element at index 4. i.e 5th element of the array a
print(a[4:7]) # Prints the element from index 4 to index 6. Note that a[4:7] means elements from 4 upto 7 (But not including 7).
print(a[4:5]) # Note that this returns an array with 1 element. But a[5] returns a scalar element

#Slicing using -ve indexing

print(a[-1]) # prints last element
print(a[-2]) # prints last but element
print(a[-5:-2]) # prints 5th ,6th and 7th element. i.e -5,-4,-3



[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744 3375 4096 4913 5832 6859 8000 9261]
64
[ 64 125 216]
[64]
9261
8000
[4913 5832 6859]


### iterating elements in a array:-

In [ ]:

import numpy as np
a=np.arange(12).reshape(4,3)**2 # Create an array "a" with square of numbers from 0 to 11.
print(a)

for i in a:
    print(i)


[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[0 1 4]
[ 9 16 25]
[36 49 64]
[ 81 100 121]


## v) Matrix operations on NumPy arrays

In [ ]:
import numpy as np
a = np.array( [[22,4],[48,22]] )
b = np.array( [[7,7],[48,4]] )

print(np.add(a,b))  # adding of matrices

print(np.subtract(a,b))  # subtraction of matrices

print(np.multiply(a,b)) # product of matrices

print(np.divide(a,b)) # division of matrices


[[29 11]
 [96 26]]
[[15 -3]
 [ 0 18]]
[[ 154   28]
 [2304   88]]
[[3.14285714 0.57142857]
 [1.         5.5       ]]
